% This code generates a mp4 video with the bounding box generated by a
% tracker
%Roger Gomez Nieto - February 16 2018



addpath('C:\Dropbox\git');
clc;
close all;
tic
% gt_Initial = importdata('C:\Users\DeepLearning_PUJ\Downloads\020ExFo_IndPW_FQ_C3results_DeepSTRCF.txt');
gt_Initial = f1;
Original_Video='G:\AppDrivenTracker\videos70\video63.mp4';
Video_BB_Name=strcat(Original_Video,'_BB.mp4');

vid1 = VideoReader(Original_Video);
writerObj1 = VideoWriter(Video_BB_Name,'MPEG-4');
writerObj1.FrameRate=vid1.FrameRate;
Number_Of_Frames=vid1.NumberOfFrames
open(writerObj1);
for i = 1 : vid1.NumberOfFrames
    im=read(vid1,i);
%                 f = @() rectangle('position',[x y w h]);
    f = @() rectangle('position',gt_Initial(i,:));
    params = {'linewidth',2,'edgecolor','r'};
    imgOut = insertInImage(im,f,params);
    writeVideo(writerObj1,imgOut);
    i
end
close(writerObj1)
toc
