% This code generates a mp4 video with the bounding box generated by a
% tracker
%Roger Gomez Nieto - February 16 2018

%TRACKER 1 --> LADCF

addpath('C:\Dropbox\git');
clear all;
clc;
close all;
tic
video_name = '0274Pri_IndWL_C1';
name_GT= strcat('C:\Dropbox\Javeriana\datasets\AD-VSD\surveillanceVideosDataset\surveillanceVideosGT\',video_name,'_gt.txt');
% gt_Initial = importdata(0274Pri_IndWL_C1_gt.txt');
gt_Initial = importdata(name_GT);

file_tracker_results  = strcat('C:\Dropbox\Javeriana\current_work\tracker_prediction\Results\Set8VIDEOS_ADSVD/',video_name,'.mat');
% all_trackers_results = importdata('C:\Dropbox\Javeriana\current_work\tracker_prediction\Results\Set8VIDEOS_ADSVD/0274Pri_IndWL_C1.mat');
all_trackers_results = importdata(file_tracker_results);

tracker1 = all_trackers_results.ladcf_BB;
tracker2 = all_trackers_results.MFT_BB;
tracker3= all_trackers_results.DeepSTRCF_BB;
tracker4 = all_trackers_results.CPT_BB;
tracker5 = all_trackers_results.DLST_BB;
tracker6= all_trackers_results.RCO_BB;
tracker7= all_trackers_results.SRCT_BB;

% gt_Initial = f1;
% Original_Video='C:\Dropbox\Javeriana\current_work\tracker_prediction\Test_Videos_Tracking\video1_pristine\video1.mp4';
name_original_video = strcat('C:\Dropbox\Javeriana\datasets\AD-VSD\surveillanceVideosDataset\surveillanceVideos/',video_name,'.mp4');
% Original_Video = 'C:\Dropbox\Javeriana\datasets\AD-VSD\surveillanceVideosDataset\surveillanceVideos/0274Pri_IndWL_C1.mp4';
Original_Video = name_original_video;

Video_BB_Name=strcat(Original_Video,'_BB.mp4');
line_width_code = 6; %el ancho de la linea con el que se mostrará el BOunding Box


vid1 = VideoReader(Original_Video);
writerObj1 = VideoWriter(Video_BB_Name,'MPEG-4');
writerObj1.FrameRate=vid1.FrameRate;
Number_Of_Frames=vid1.NumberOfFrames
open(writerObj1);

%esto no se puede paralelizar, ya se intentó y sale error
for i = 350 : vid1.NumberOfFrames
% for i = 1 : vid1.NumberOfFrames
    im=read(vid1,i);
    %                 f = @() rectangle('position',[x y w h]);
    f0 = @() rectangle('position',gt_Initial(i,:));
    params0 = {'linewidth',line_width_code,'edgecolor','r'};
    
    %Posición del Tracker 1
    f1 = @() rectangle('position',tracker1(i,:));
    params1 = {'linewidth',line_width_code,'edgecolor',[86 180 233]/255};
    
    imgOut = insertInImage(im,f0,params0);
    if i ==1
        FirstImage_withGT =...
            insertText(imgOut, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
        imshow(FirstImage_withGT)
        %         saveas(FirstImage_withGT,'Barchart','eps')
        imwrite(FirstImage_withGT,'prueba.png');
    end
    imgOut2 = insertInImage(imgOut,f1,params1);
    %     imshow(imgOut2)
    
    %     RGB = insertText(imgOut2, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
    
    %tracker 2
    f2 = @() rectangle('position',tracker2(i,:));
    params2 = {'linewidth',line_width_code,'edgecolor',[0 158 115]/255};
    Img_T2 = insertInImage(imgOut2,f2,params2);
    %     RGB = insertText(Img_T2, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
    
    %tracker 3
    f3 = @() rectangle('position',tracker3(i,:));
    params3 = {'linewidth',line_width_code,'edgecolor',[240 228 66]/255};%yellow
    Img_T3 = insertInImage(Img_T2,f3,params3);
    %     RGB = insertText(Img_T3, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
    
    %tracker 4
    f4 = @() rectangle('position',tracker4(i,:));
    params4 = {'linewidth',line_width_code,'edgecolor',[0 114 178]/255};%Blue
    Img_T4 = insertInImage(Img_T3,f4,params4);
%     RGB = insertText(Img_T4, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
    
    %tracker 5
    f5 = @() rectangle('position',tracker5(i,:));
    params5 = {'linewidth',line_width_code,'edgecolor',[213 94 0]/255};%Vermillion
    Img_T5 = insertInImage(Img_T4,f5,params5);
%     RGB = insertText(Img_T5, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
    
    %tracker 6
    f6 = @() rectangle('position',tracker6(i,:));
    params6 = {'linewidth',line_width_code,'edgecolor',[204 121 167]/255};%Purple
    Img_T6 = insertInImage(Img_T5,f6,params6);
%     RGB = insertText(Img_T6, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
    
    %tracker 7
    f7 = @() rectangle('position',tracker7(i,:));
    params7 = {'linewidth',line_width_code,'edgecolor',[255 255 255]/255};%Black
    Img_T7 = insertInImage(Img_T6,f7,params7);
    RGB = insertText(Img_T7, [10 80],strcat('#',num2str(i)),'TextColor','yellow','FontSize',56,'BoxOpacity',0,'AnchorPoint','LeftBottom');
%     
    
    
    imshow(RGB)
    writeVideo(writerObj1,imgOut);
    i
    if i==10 || i== 30 || i== 45
        name_image_2_save = strcat(video_name,'_frame',num2str(i),'.png');
        imwrite(RGB,name_image_2_save);
    end
end
close(writerObj1)
toc
